### PR TITLE
Read2d bugfix8

### PR DESCRIPTION
**Pull request by luizhdasilva**
Solve bug #8 by adding a if statement to access 2D variables after masking.

### CODE REVIEW

**Comment by jeenriquez** [comment]
Hey Luiz, 
Looking good!
Question, in line 67.  Wondering when is it that you have that case and why is it [0, :, :, 0], instead of [0, :, :, idepth]

**Comment by luizhdasilva** [comment]
> Hey @luizhdasilva, Looking good! Question, in line 67. Wondering when is it that you have that case and why is it [0, :, :, 0], instead of [0, :, :, idepth]

This address the fact that the masking method currently applied creates a artificial third dimensions (depth) in a 2D variable. So, using [0, :, :, 0], assures that the user are plotting all the data in the selected area. Using "idepth" would plot a figure that masks out a pseudo bathymetry depending on a depth dimension that actually doesn't exists in a 2D variable.

**Comment by jeenriquez** [comment]
I was thinking the 2D case was solved in lines 70-71. But maybe I'm not seeing something. Lets talk in hour next meeting. :)

**Review by jeenriquez — APPROVED** [review]
Reviewed. Working.

**Pull request merged**
